//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWave.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieWave.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not found.
        /// </summary>
        internal static string AttachmentNotFound {
            get {
                return ResourceManager.GetString("AttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner not found.
        /// </summary>
        internal static string BannerNotFound {
            get {
                return ResourceManager.GetString("BannerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners not found.
        /// </summary>
        internal static string BannersNotFound {
            get {
                return ResourceManager.GetString("BannersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries not found.
        /// </summary>
        internal static string CountriesNotFound {
            get {
                return ResourceManager.GetString("CountriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exists.
        /// </summary>
        internal static string CountryAlreadyExists {
            get {
                return ResourceManager.GetString("CountryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found.
        /// </summary>
        internal static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while seeding database.
        /// </summary>
        internal static string ErrorSeedingDB {
            get {
                return ResourceManager.GetString("ErrorSeedingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user.
        /// </summary>
        internal static string FailedToCreateUser {
            get {
                return ResourceManager.GetString("FailedToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client request.
        /// </summary>
        internal static string InvalidClientRequest {
            get {
                return ResourceManager.GetString("InvalidClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaItem already exists.
        /// </summary>
        internal static string MediaItemAlreadyExists {
            get {
                return ResourceManager.GetString("MediaItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaItem not found.
        /// </summary>
        internal static string MediaItemNotFound {
            get {
                return ResourceManager.GetString("MediaItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaItems not found.
        /// </summary>
        internal static string MediaItemsNotFound {
            get {
                return ResourceManager.GetString("MediaItemsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaItemType not found.
        /// </summary>
        internal static string MediaItemTypeNotFound {
            get {
                return ResourceManager.GetString("MediaItemTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaItemTypes not found.
        /// </summary>
        internal static string MediaItemTypesNotFound {
            get {
                return ResourceManager.GetString("MediaItemTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not equals password confirm.
        /// </summary>
        internal static string PasswordNotEqualsPasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordNotEqualsPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestrictedRating not found.
        /// </summary>
        internal static string RestrictedRatingNotFound {
            get {
                return ResourceManager.GetString("RestrictedRatingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestrictedRatings not found.
        /// </summary>
        internal static string RestrictedRatingsNotFound {
            get {
                return ResourceManager.GetString("RestrictedRatingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not found.
        /// </summary>
        internal static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses not found.
        /// </summary>
        internal static string StatusesNotFound {
            get {
                return ResourceManager.GetString("StatusesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not found.
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio already exists.
        /// </summary>
        internal static string StudioAlreadyExists {
            get {
                return ResourceManager.GetString("StudioAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio not found.
        /// </summary>
        internal static string StudioNotFound {
            get {
                return ResourceManager.GetString("StudioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studios not found.
        /// </summary>
        internal static string StudiosNotFound {
            get {
                return ResourceManager.GetString("StudiosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists.
        /// </summary>
        internal static string TagAlreadyExists {
            get {
                return ResourceManager.GetString("TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found.
        /// </summary>
        internal static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags not found.
        /// </summary>
        internal static string TagsNotFound {
            get {
                return ResourceManager.GetString("TagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists this role.
        /// </summary>
        internal static string UserAlreadyExistsThisRole {
            get {
                return ResourceManager.GetString("UserAlreadyExistsThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation failed.
        /// </summary>
        internal static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        internal static string InvalidFile
        {
	        get
	        {
		        return ResourceManager.GetString("InvalidFile", resourceCulture);
	        }
        }
	}
}
